<<<<<<< HEAD
name: Elasticsearch 5.5.2
description: |
  Elasticsearch, you
=======
name: Elasticsearch 552
description: |
  Elasticsearch
>>>>>>> c19e262a6d1a06e908ef2dc0a2669bcfa7bbc3d2
version: 5.5.2
category: ELK
