<<<<<<< HEAD
name: Kibana 5.5.2
description: |
  Kibana, you know 
version: 5.5.2
=======
name: "Kibana 5"
description: "Visualization dashboard"
version: "5.2.2"
>>>>>>> c19e262a6d1a06e908ef2dc0a2669bcfa7bbc3d2
category: ELK
